CREATE TABLE IF NOT EXISTS FileTransfer (
ID integer  NOT NULL  PRIMARY KEY AUTOINCREMENT DEFAULT 0,
FileID Varchar(64) DEFAULT '',
Type INTEGER DEFAULT 0,
Status INTEGER DEFAULT 0,
Url TEXT DEFAULT '',
Vcard TEXT DEFAULT '',
FileName TEXT DEFAULT '',
FileDate Varchar(64) DEFAULT '',
FileSize Double DEFAULT 0,
SizePerSecond Double DEFAULT 0);

CREATE TABLE IF NOT EXISTS FileReceive (
ID integer  NOT NULL  PRIMARY KEY AUTOINCREMENT DEFAULT 0,
FileID Varchar(64) DEFAULT '',
Type INTEGER DEFAULT 0,
Status INTEGER DEFAULT 0,
Url TEXT DEFAULT '',
Vcard TEXT DEFAULT '',
FileName TEXT DEFAULT '',
FileDate Varchar(64) DEFAULT '',
FileSize Double DEFAULT 0,
SizePerSecond Double DEFAULT 0);